CREATE TABLE users (
ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
email VARCHAR (200) NOT NULL UNIQUE,
password VARCHAR (60) NOT NULL,
first_name VARCHAR (100) NOT NULL,
surname VARCHAR (100) NOT NULL,
roles SMALLINT NOT NULL CHECK (roles IN (0,1))

);

CREATE TABLE categories (

ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
descritpion VARCHAR (200) NOT NULL,
url_image VARCHAR (255) NOT NULL,
qualification VARCHAR (100) NOT NULL UNIQUE

);

CREATE TABLE car (

ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_car VARCHAR (100) NOT NULL,
category_id BIGINT NOT NULL,
FOREIGN KEY (category_id) REFERENCES categories(ID)

);
