CREATE TABLE IF NOT EXISTS roles (
ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name_role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (

ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
email VARCHAR (200) NOT NULL UNIQUE,
password VARCHAR (60) NOT NULL,
first_name VARCHAR (100) NOT NULL,
surname VARCHAR (100) NOT NULL,
roles_id BIGINT NOT NULL,
FOREIGN KEY (roles_id) REFERENCES roles(ID)

);

CREATE TABLE IF NOT EXISTS categories (

ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
descritpion VARCHAR (200) NOT NULL,
url_image VARCHAR (255) NOT NULL,
qualification VARCHAR (100) NOT NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS cities (

ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_city VARCHAR (100) NOT NULL,
country VARCHAR(100) NOT NULL

);



CREATE TABLE IF NOT EXISTS cars (
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_car VARCHAR (100) NOT NULL,
descritpion VARCHAR (2000) NOT NULL,
price DECIMAL (10,2) NOT NULL,
year_car INT NOT NULL,
highlight BOOLEAN DEFAULT false NOT NULL,
category_id BIGINT NOT NULL,
city_id BIGINT NOT NULL,
FOREIGN KEY (category_id) REFERENCES categories(ID),
FOREIGN KEY(city_id) REFERENCES cities(ID)

);

CREATE TABLE IF NOT EXISTS bookings (
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
start_date DATE,
start_time TIME,
end_date DATE,
car_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
FOREIGN KEY(car_id) REFERENCES cars(ID),
FOREIGN KEY(user_id) REFERENCES users(ID)

);


CREATE TABLE IF NOT EXISTS caracteristics (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name_caracteristcs VARCHAR(255) NOT NULL,
  icon VARCHAR(255) NOT NULL,
  unit_of_measurement VARCHAR(25) NULL
);


CREATE TABLE IF NOT EXISTS car_caracteristics (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  car_id BIGINT NOT NULL,
  caracteristics_id BIGINT NOT NULL,
  value_caracteristic VARCHAR(50) NULL,
  FOREIGN KEY (car_id) REFERENCES cars(id),
  FOREIGN KEY (caracteristics_id) REFERENCES caracteristics(id)
);


CREATE TABLE IF NOT EXISTS images (

ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR (100) NOT NULL,
url VARCHAR (255) NOT NULL,
car_id BIGINT NOT NULL,
FOREIGN KEY (car_id) REFERENCES cars(ID)

);

CREATE TABLE IF NOT EXISTS contact_us_message (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR (200) NOT NULL,
  title VARCHAR (300) NOT NULL,
  body VARCHAR (6000) NOT NULL
);
